import { defineType, defineField } from "sanity";

export default defineType({
  name: "artwork",
  title: "Gallery",
  type: "document",
  icon: () => "🎨",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      description: "Name of the piece, e.g. 'Bella — Pastel Portrait'",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "URL Slug",
      type: "slug",
      options: { source: "title", maxLength: 96 },
      description: "Click Generate to create automatically from the title",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "image",
      title: "Photo",
      type: "image",
      options: { hotspot: true },
      description: "Upload a photo of the artwork",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 3,
      description: "Optional — a short note about this piece",
    }),
    defineField({
      name: "medium",
      title: "Medium",
      type: "array",
      of: [{ type: "string" }],
      description: "What was this made with?",
      options: {
        list: [
          { title: "Pastel", value: "pastel" },
          { title: "Watercolour", value: "watercolour" },
          { title: "Pencil", value: "pencil" },
          { title: "Oil", value: "oil" },
          { title: "Charcoal", value: "charcoal" },
          { title: "Mixed Media", value: "mixed media" },
          { title: "Acrylic", value: "acrylic" },
          { title: "Ink", value: "ink" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "subject",
      title: "Subject",
      type: "array",
      of: [{ type: "string" }],
      description: "What is this a picture of?",
      options: {
        list: [
          { title: "Animals", value: "animals" },
          { title: "Dogs", value: "dogs" },
          { title: "Cats", value: "cats" },
          { title: "Horses", value: "horses" },
          { title: "Birds", value: "birds" },
          { title: "Wildlife", value: "wildlife" },
          { title: "People", value: "people" },
          { title: "Landscape", value: "landscape" },
          { title: "Seascapes", value: "seascapes" },
          { title: "Still Life", value: "still life" },
          { title: "Food", value: "food" },
          { title: "Flowers", value: "flowers" },
          { title: "Buildings", value: "buildings" },
        ],
      },
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "featured",
      title: "Show on Homepage",
      type: "boolean",
      description: "Turn this on to feature this piece on the homepage",
      initialValue: false,
    }),
    defineField({
      name: "date",
      title: "Date Added",
      type: "date",
      initialValue: () => new Date().toISOString().split("T")[0],
      validation: (rule) => rule.required(),
    }),
  ],
  orderings: [
    { title: "Newest First", name: "dateDesc", by: [{ field: "date", direction: "desc" }] },
    { title: "Title A-Z", name: "titleAsc", by: [{ field: "title", direction: "asc" }] },
  ],
  preview: {
    select: { title: "title", media: "image", subtitle: "date" },
  },
});
